INSERT INTO books VALUES (1, 'The Colour of Magic', '2012', 'Corgi', 'img/covers/tp_the_colour_of_magic.jpg', 3, 288);
INSERT INTO books VALUES (2, 'Equal Rites', '2012', 'Corgi', 'img/covers/tp_equal_rites.jpg', 3, 288);
INSERT INTO books VALUES (3, 'The Long Cosmos', '2016', 'Doubleday', 'img/covers/tp_sb_the_long_cosmos.jpg', 4, 400);
INSERT INTO books VALUES (4, 'Finders Keepers', '2016', 'Hodder Paperbacks', 'img/covers/sk_finders_keepers.jpg', 2, 400);
INSERT INTO books VALUES (5, 'Living Death', '2016', 'Head of Zeus', 'img/covers/gm_living_death.jpg', 2, 368);
INSERT INTO books VALUES (6, 'Dead Girls Dancing', '2017', 'Head of Zeus', 'img/covers/gm_dead_girls_dancing.jpg', 2, 368);
INSERT INTO books VALUES (7, 'McFall', '2013', '47North', 'img/covers/sn_mcfall.jpg', 1, 421);
INSERT INTO books VALUES (8, 'The Red Church', '2014', 'Haunted Computer Books', 'img/covers/sn_the_red_church.jpg', 1, 288);
INSERT INTO books VALUES (9, 'Drummer Boy', '2010', 'Haunted Computer Books', 'img/covers/sn_drummer_boy.jpg', 1, 305);
INSERT INTO books VALUES (10, 'The Hobbit', '2001', 'HMH Books for Young Readers', 'img/covers/jrrt_the_hobbit.jpg', 3, 333);
INSERT INTO books VALUES (11, 'Obelisk', '2016', 'Gollancz', 'img/covers/sb_obelisk.jpg', 4, 320);
